name: Latest blog posts workflow
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ZAGRODZKI-ME"
          feed_list: "https://www.zagrodzki.me/feed"
          commit_message: "Update zagrodzki.me blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
